// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ1mjfaJy8kmLUi3VMSRtPPJkIch8B_lM',
    appId: '1:759937260165:web:473e679a2e66425c53a7ec',
    messagingSenderId: '759937260165',
    projectId: 'dots-and-boxes-53a01',
    authDomain: 'dots-and-boxes-53a01.firebaseapp.com',
    storageBucket: 'dots-and-boxes-53a01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy1NaHYkIwp-ovFRG54w0snezVHFSmM7c',
    appId: '1:759937260165:android:48dfc80cab4563ee53a7ec',
    messagingSenderId: '759937260165',
    projectId: 'dots-and-boxes-53a01',
    storageBucket: 'dots-and-boxes-53a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5D4omtOGuVDWet3ga1GHDTrhmW8PT98k',
    appId: '1:759937260165:ios:5948a026902899f053a7ec',
    messagingSenderId: '759937260165',
    projectId: 'dots-and-boxes-53a01',
    storageBucket: 'dots-and-boxes-53a01.firebasestorage.app',
    iosBundleId: 'com.example.jeuCarre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5D4omtOGuVDWet3ga1GHDTrhmW8PT98k',
    appId: '1:759937260165:ios:5948a026902899f053a7ec',
    messagingSenderId: '759937260165',
    projectId: 'dots-and-boxes-53a01',
    storageBucket: 'dots-and-boxes-53a01.firebasestorage.app',
    iosBundleId: 'com.example.jeuCarre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ1mjfaJy8kmLUi3VMSRtPPJkIch8B_lM',
    appId: '1:759937260165:web:efea3de236d1e49c53a7ec',
    messagingSenderId: '759937260165',
    projectId: 'dots-and-boxes-53a01',
    authDomain: 'dots-and-boxes-53a01.firebaseapp.com',
    storageBucket: 'dots-and-boxes-53a01.firebasestorage.app',
  );
}
