// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA88UVSoLuhmUuYrlP_NlKPYwC6ENnxGUA',
    appId: '1:691944741018:web:6638ad0b3bf38da188a723',
    messagingSenderId: '691944741018',
    projectId: 'shikaku-aec0c',
    authDomain: 'shikaku-aec0c.firebaseapp.com',
    storageBucket: 'shikaku-aec0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsYlYyqLO-bTErU9SbmDbHox3QX3DSjlQ',
    appId: '1:691944741018:android:1871d3c3c4dbdab188a723',
    messagingSenderId: '691944741018',
    projectId: 'shikaku-aec0c',
    storageBucket: 'shikaku-aec0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR2IcsTOV752B6bQyikg_P4eN07rmGe78',
    appId: '1:691944741018:ios:36393bacbbd87bac88a723',
    messagingSenderId: '691944741018',
    projectId: 'shikaku-aec0c',
    storageBucket: 'shikaku-aec0c.firebasestorage.app',
    iosBundleId: 'com.example.jeuCarre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR2IcsTOV752B6bQyikg_P4eN07rmGe78',
    appId: '1:691944741018:ios:36393bacbbd87bac88a723',
    messagingSenderId: '691944741018',
    projectId: 'shikaku-aec0c',
    storageBucket: 'shikaku-aec0c.firebasestorage.app',
    iosBundleId: 'com.example.jeuCarre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA88UVSoLuhmUuYrlP_NlKPYwC6ENnxGUA',
    appId: '1:691944741018:web:3502e422947b5db588a723',
    messagingSenderId: '691944741018',
    projectId: 'shikaku-aec0c',
    authDomain: 'shikaku-aec0c.firebaseapp.com',
    storageBucket: 'shikaku-aec0c.firebasestorage.app',
  );
}
